database:
  host: 192.168.192.208
  port: 3306
  user: weather_colly
  password: fREhtsJxCKKyFY6F
  database: weather_colly
  options: charset=utf8mb4&parseTime=true&loc=Asia%2fShanghai

crontab:
  open: true
  works:
    - name: colly_weather
      crontab: "0 30 * * *"